/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passtrunk;

import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yendy
 */
public class AddMembToTeam extends javax.swing.JFrame {

    private DashboardFrame dashboard;
    private int teamIndex;

    public void setDashboard(DashboardFrame dashboard) {
        this.dashboard = dashboard;
    }

    public void setTeamIndex(int teamIndex) {
        this.teamIndex = teamIndex;
    }
    
    
    /**
     * Creates new form AddMembToTeam
     */
    public AddMembToTeam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameSearchTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userIDTF = new javax.swing.JTextField();
        searchMembButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        addUserButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Add Member");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("You can look up a member by username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Or just type in the user ID (User ID is available under settings)");

        searchMembButton.setBackground(new java.awt.Color(64, 138, 201));
        searchMembButton.setForeground(new java.awt.Color(255, 255, 255));
        searchMembButton.setText("Search");
        searchMembButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMembButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(0, 128, 0));

        addUserButton.setBackground(new java.awt.Color(64, 138, 201));
        addUserButton.setForeground(new java.awt.Color(255, 255, 255));
        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(64, 138, 201));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(usernameSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchMembButton))
                        .addComponent(userIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addUserButton))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMembButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMembButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMembButtonActionPerformed
        if(usernameSearchTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: Please type a user name to search.", "ErrorBox: ", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                String uname = usernameSearchTF.getText();
                String url = "https://passtrunk.com/api/user/search";
                String reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("username", "UTF-8")+"="+URLEncoder.encode(uname,"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                RequestsHTTP reqhttp = new RequestsHTTP(url,"GET",reqbody);
                boolean success = reqhttp.doTransaction("searchuserid", 0);
                if(success){
                    resultLabel.setText("Username found click Add User to proceed");
                    userIDTF.setText(String.valueOf(reqhttp.getSearchUserID()));
                }
                else{
                    resultLabel.setForeground(Color.red);
                    resultLabel.setText("Username not found.");
                    userIDTF.setText("");
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(AddMembToTeam.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchMembButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        if(userIDTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: Please type a user ID to add.", "ErrorBox: ", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                int userID = Integer.valueOf(userIDTF.getText());
                String url = "https://passtrunk.com/api/team/member";
                String reqbody = URLEncoder.encode("ownerid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("newuserid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(userID),"UTF-8")
                        +"&"+URLEncoder.encode("teamname", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.teams.get(teamIndex).getName(),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                RequestsHTTP reqhttp = new RequestsHTTP(url,"POST",reqbody);
                boolean success = reqhttp.doTransaction("", 0);
                if(success){
                    JOptionPane.showMessageDialog(null, "User added successfuly", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    if(reqhttp.getCode() == 202){
                        JOptionPane.showMessageDialog(null, "Info: The user is already a member.", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Error: User ccould not be added.", "ErrorBox: ", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(AddMembToTeam.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dashboard.setEnabled(true);
        dashboard.PopulateManTeamLists();
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMembToTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMembToTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMembToTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMembToTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMembToTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton searchMembButton;
    private javax.swing.JTextField userIDTF;
    private javax.swing.JTextField usernameSearchTF;
    // End of variables declaration//GEN-END:variables
}
