/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passtrunk;

import SecurityED.AESEncryptDecrypt;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yendy
 */
public class EditFrame extends javax.swing.JFrame {

    DashboardFrame df;
    int pos;
    BankAccountCredential bank;
    CreditCardCredential credCard;
    EmailCredential email;
    LoginCredential login;
    SoftwareLicenseCredential softl;
    SocialSecurityCredential ssn;
    WebsiteCredential web;
    WirelessCredential wireless;
    CustomCredential cust;

    public void setDf(DashboardFrame df) {
        this.df = df;
    }
    /**
     * Creates new form EditFrame
     */
    public EditFrame() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        credNameTypeLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        editBankAcctPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bEditNameTF = new javax.swing.JTextField();
        bEditUrlTF = new javax.swing.JTextField();
        bEditUsernameTF = new javax.swing.JTextField();
        bEditRoutNumTF = new javax.swing.JTextField();
        bEditAcctNumTF = new javax.swing.JTextField();
        bEditPasswordTF = new javax.swing.JTextField();
        editCredCardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ccEditBankNameTF = new javax.swing.JTextField();
        ccEditNumberTF = new javax.swing.JTextField();
        ccEditExpDateTF = new javax.swing.JTextField();
        ccEditCardOwnerTF = new javax.swing.JTextField();
        ccEditCcvTF = new javax.swing.JTextField();
        ccEditTypeTF = new javax.swing.JTextField();
        editEmailPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        eEditLogPageTF = new javax.swing.JTextField();
        eEditAddressTF = new javax.swing.JTextField();
        eEditPasswordTF = new javax.swing.JTextField();
        editLoginPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lEditUsernameTF = new javax.swing.JTextField();
        lEditAssocEmailTF = new javax.swing.JTextField();
        lEditPasswordTF = new javax.swing.JTextField();
        editSoftLicPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        slEditSoftNameTF = new javax.swing.JTextField();
        slEditKeyTF = new javax.swing.JTextField();
        slEditWebUrlTF = new javax.swing.JTextField();
        slEditExpDateTF = new javax.swing.JTextField();
        editSsnPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ssnEditOwnerTF = new javax.swing.JTextField();
        ssnEditNumberTF = new javax.swing.JTextField();
        editWebsitePanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        weEditNameTF = new javax.swing.JTextField();
        weEditUrlTF = new javax.swing.JTextField();
        weEditUsernameTF = new javax.swing.JTextField();
        weEditAssocEmailTF = new javax.swing.JTextField();
        weEditPasswordTF = new javax.swing.JTextField();
        editWirelessPanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        wiEditNameTF = new javax.swing.JTextField();
        wiEditEncryptionTF = new javax.swing.JTextField();
        wiEditUsernameTF = new javax.swing.JTextField();
        wiEditPasswordTF = new javax.swing.JTextField();
        editCustomPanel = new javax.swing.JPanel();
        saveEditButton = new javax.swing.JButton();
        closeEditButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        credNameTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        editBankAcctPanel.setAutoscrolls(true);

        jLabel2.setText("Bank Name:");

        jLabel3.setText("Bank Url:");

        jLabel4.setText("Bank Username:");

        jLabel5.setText("Bank Password:");

        jLabel6.setText("Bank Routing Number:");

        jLabel7.setText("Bank Account Number:");

        javax.swing.GroupLayout editBankAcctPanelLayout = new javax.swing.GroupLayout(editBankAcctPanel);
        editBankAcctPanel.setLayout(editBankAcctPanelLayout);
        editBankAcctPanelLayout.setHorizontalGroup(
            editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBankAcctPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bEditUrlTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(bEditUsernameTF)
                    .addComponent(bEditRoutNumTF)
                    .addComponent(bEditAcctNumTF)
                    .addComponent(bEditNameTF)
                    .addComponent(bEditPasswordTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editBankAcctPanelLayout.setVerticalGroup(
            editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBankAcctPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bEditNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bEditUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bEditUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bEditPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bEditRoutNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editBankAcctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bEditAcctNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editBankAcctPanel, "card2");

        editCredCardPanel.setAutoscrolls(true);

        jLabel1.setText("Bank Name:");

        jLabel8.setText("Credit Card Number:");

        jLabel9.setText("Expiration Date:");

        jLabel10.setText("Card Owner:");

        jLabel11.setText("CCV:");

        jLabel12.setText("Card Type:");

        javax.swing.GroupLayout editCredCardPanelLayout = new javax.swing.GroupLayout(editCredCardPanel);
        editCredCardPanel.setLayout(editCredCardPanelLayout);
        editCredCardPanelLayout.setHorizontalGroup(
            editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCredCardPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccEditBankNameTF)
                    .addComponent(ccEditNumberTF)
                    .addComponent(ccEditExpDateTF)
                    .addComponent(ccEditCardOwnerTF)
                    .addComponent(ccEditCcvTF)
                    .addComponent(ccEditTypeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editCredCardPanelLayout.setVerticalGroup(
            editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCredCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ccEditBankNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ccEditNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ccEditExpDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ccEditCardOwnerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ccEditCcvTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCredCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ccEditTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editCredCardPanel, "card3");

        jLabel13.setText("Email Login Page:");

        jLabel14.setText("Email Address:");

        jLabel15.setText("Password:");

        javax.swing.GroupLayout editEmailPanelLayout = new javax.swing.GroupLayout(editEmailPanel);
        editEmailPanel.setLayout(editEmailPanelLayout);
        editEmailPanelLayout.setHorizontalGroup(
            editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmailPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eEditLogPageTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(eEditAddressTF)
                    .addComponent(eEditPasswordTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editEmailPanelLayout.setVerticalGroup(
            editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(eEditLogPageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(eEditAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(eEditPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editEmailPanel, "card4");

        jLabel16.setText("Username:");

        jLabel17.setText("Password:");

        jLabel18.setText("Associated Email:");

        javax.swing.GroupLayout editLoginPanelLayout = new javax.swing.GroupLayout(editLoginPanel);
        editLoginPanel.setLayout(editLoginPanelLayout);
        editLoginPanelLayout.setHorizontalGroup(
            editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLoginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lEditUsernameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(lEditAssocEmailTF)
                    .addComponent(lEditPasswordTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editLoginPanelLayout.setVerticalGroup(
            editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lEditUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lEditPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lEditAssocEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editLoginPanel, "card5");

        jLabel19.setText("Software Name:");

        jLabel20.setText("Software Key:");

        jLabel21.setText("Website Url:");

        jLabel22.setText("Expiration Date:");

        javax.swing.GroupLayout editSoftLicPanelLayout = new javax.swing.GroupLayout(editSoftLicPanel);
        editSoftLicPanel.setLayout(editSoftLicPanelLayout);
        editSoftLicPanelLayout.setHorizontalGroup(
            editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSoftLicPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slEditSoftNameTF)
                    .addComponent(slEditKeyTF)
                    .addComponent(slEditWebUrlTF)
                    .addComponent(slEditExpDateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editSoftLicPanelLayout.setVerticalGroup(
            editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSoftLicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(slEditSoftNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(slEditKeyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(slEditWebUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editSoftLicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(slEditExpDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editSoftLicPanel, "card6");

        jLabel23.setText("Owner:");

        jLabel24.setText("SSN:");

        javax.swing.GroupLayout editSsnPanelLayout = new javax.swing.GroupLayout(editSsnPanel);
        editSsnPanel.setLayout(editSsnPanelLayout);
        editSsnPanelLayout.setHorizontalGroup(
            editSsnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSsnPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editSsnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editSsnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ssnEditOwnerTF)
                    .addComponent(ssnEditNumberTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editSsnPanelLayout.setVerticalGroup(
            editSsnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSsnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editSsnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ssnEditOwnerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editSsnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ssnEditNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editSsnPanel, "card7");

        jLabel25.setText("Website Name:");

        jLabel26.setText("Website Url:");

        jLabel27.setText("Username:");

        jLabel28.setText("Password:");

        jLabel29.setText("Associated Email:");

        javax.swing.GroupLayout editWebsitePanelLayout = new javax.swing.GroupLayout(editWebsitePanel);
        editWebsitePanel.setLayout(editWebsitePanelLayout);
        editWebsitePanelLayout.setHorizontalGroup(
            editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWebsitePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weEditNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(weEditUrlTF)
                    .addComponent(weEditUsernameTF)
                    .addComponent(weEditAssocEmailTF)
                    .addComponent(weEditPasswordTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editWebsitePanelLayout.setVerticalGroup(
            editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWebsitePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(weEditNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(weEditUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(weEditUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(weEditPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWebsitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(weEditAssocEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editWebsitePanel, "card8");

        jLabel30.setText("WiFi Name:");

        jLabel31.setText("Encryption:");

        jLabel32.setText("Username:");

        jLabel33.setText("Password:");

        javax.swing.GroupLayout editWirelessPanelLayout = new javax.swing.GroupLayout(editWirelessPanel);
        editWirelessPanel.setLayout(editWirelessPanelLayout);
        editWirelessPanelLayout.setHorizontalGroup(
            editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWirelessPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wiEditNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(wiEditEncryptionTF)
                    .addComponent(wiEditUsernameTF)
                    .addComponent(wiEditPasswordTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editWirelessPanelLayout.setVerticalGroup(
            editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWirelessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(wiEditNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(wiEditEncryptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(wiEditUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editWirelessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(wiEditPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLayeredPane1.add(editWirelessPanel, "card9");

        editCustomPanel.setAutoscrolls(true);

        javax.swing.GroupLayout editCustomPanelLayout = new javax.swing.GroupLayout(editCustomPanel);
        editCustomPanel.setLayout(editCustomPanelLayout);
        editCustomPanelLayout.setHorizontalGroup(
            editCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        editCustomPanelLayout.setVerticalGroup(
            editCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jLayeredPane1.add(editCustomPanel, "card10");

        saveEditButton.setBackground(new java.awt.Color(64, 138, 201));
        saveEditButton.setForeground(new java.awt.Color(255, 255, 255));
        saveEditButton.setText("Save");
        saveEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditButtonActionPerformed(evt);
            }
        });

        closeEditButton.setBackground(new java.awt.Color(64, 138, 201));
        closeEditButton.setForeground(new java.awt.Color(255, 255, 255));
        closeEditButton.setText("Close");
        closeEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeEditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credNameTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveEditButton)
                .addGap(18, 18, 18)
                .addComponent(closeEditButton)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(credNameTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveEditButton)
                    .addComponent(closeEditButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeEditButtonActionPerformed
        df.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_closeEditButtonActionPerformed

    private void saveEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditButtonActionPerformed
        try {  
            String uName = RequestsHTTP.user.getUsername();
            String uToken = RequestsHTTP.user.getToken();
            String key = uName.substring(0, 2) + uToken.substring(0,5) + uName.substring(2) + uToken.substring(5);
            String url ="";
            String reqbody = "";
            if(editBankAcctPanel.isVisible()){  
                url = "https://passtrunk.com/api/credential/bankaccount";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("bankname", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(bEditNameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("bankurl", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(bEditUrlTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("bankusername", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(bEditUsernameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("bankpassword", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(bEditPasswordTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("routingnumber", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(bEditRoutNumTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("accountnumber", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(bEditAcctNumTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                bEditAcctNumTF.setText("");
                bEditNameTF.setText("");
                bEditPasswordTF.setText("");
                bEditUrlTF.setText("");
                bEditRoutNumTF.setText("");
                bEditUsernameTF.setText("");
                
            }
            else if(editCredCardPanel.isVisible()){
                url = "https://passtrunk.com/api/credential/creditcard";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("bankname", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ccEditBankNameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("creditcardnumber", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ccEditNumberTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("expdate", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ccEditExpDateTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("ccv", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ccEditCcvTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("owner", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ccEditCardOwnerTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("type", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ccEditTypeTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                ccEditBankNameTF.setText("");
                ccEditCardOwnerTF.setText("");
                ccEditCcvTF.setText("");
                ccEditNumberTF.setText("");
                ccEditTypeTF.setText("");
                ccEditExpDateTF.setText("");
            }else if(editEmailPanel.isVisible()){
                url = "https://passtrunk.com/api/credential/email";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("loginurl", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(eEditLogPageTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("emailaddress", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(eEditAddressTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("password", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(eEditPasswordTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                eEditAddressTF.setText("");
                eEditLogPageTF.setText("");
                eEditPasswordTF.setText("");
            }
            else if(editLoginPanel.isVisible()){
                url = "https://passtrunk.com/api/credential/login";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("username", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(lEditUsernameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("password", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(lEditPasswordTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("assocemail", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(lEditAssocEmailTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                lEditUsernameTF.setText("");
                lEditPasswordTF.setText("");
                lEditAssocEmailTF.setText("");
            }
            else if(editSoftLicPanel.isVisible()){
                url = "https://passtrunk.com/api/credential/softwarelicense";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("softwarename", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(slEditSoftNameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("softwarekey", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(slEditKeyTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("websiteurl", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(slEditWebUrlTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("expdate", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(slEditExpDateTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                slEditExpDateTF.setText("");
                slEditKeyTF.setText("");
                slEditSoftNameTF.setText("");
                slEditWebUrlTF.setText("");
            }
            else if(editSsnPanel.isVisible()){
                url = "https://passtrunk.com/api/credential/ssn";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("ownername", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ssnEditOwnerTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("ssn", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(ssnEditNumberTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                ssnEditOwnerTF.setText("");
                ssnEditNumberTF.setText("");
            }
            else if(editWebsitePanel.isVisible()){
                url = "https://passtrunk.com/api/credential/website";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("websitename", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(weEditNameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("websiteurl", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(weEditUrlTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("websiteusername", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(weEditUsernameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("websitepassword", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(weEditPasswordTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("websiteassocemail", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(weEditAssocEmailTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                //Clearing Form:
                weEditAssocEmailTF.setText("");
                weEditNameTF.setText("");
                weEditPasswordTF.setText("");
                weEditUrlTF.setText("");
                weEditUsernameTF.setText("");
            }
            else if(editWirelessPanel.isVisible()){
                url = "https://passtrunk.com/api/credential/wireless";
                reqbody = URLEncoder.encode("userid", "UTF-8")+"="+URLEncoder.encode(String.valueOf(RequestsHTTP.user.getUserID()),"UTF-8")
                        +"&"+URLEncoder.encode("name", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.credentials.get(pos).getName(),"UTF-8").replace("+", "%20")
                        +"&"+URLEncoder.encode("ssid", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(wiEditNameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("encryption", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(wiEditEncryptionTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("username", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(wiEditUsernameTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("password", "UTF-8")+"="+URLEncoder.encode(AESEncryptDecrypt.encrypt(wiEditPasswordTF.getText(), key),"UTF-8")
                        +"&"+URLEncoder.encode("token", "UTF-8")+"="+URLEncoder.encode(RequestsHTTP.user.getToken(),"UTF-8");
                wiEditEncryptionTF.setText("");
                wiEditNameTF.setText("");
                wiEditPasswordTF.setText("");
                wiEditUsernameTF.setText("");                
            }
            else{
                //custom cred:
                
            }
            RequestsHTTP reqhttp = new RequestsHTTP(url, "PUT", reqbody);
            reqhttp.doTransaction("",0);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(EditFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(EditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveEditButtonActionPerformed

    public void ShowPanel(String panel, int pos){
        this.pos = pos;
        credNameTypeLabel.setText(RequestsHTTP.user.credentials.get(pos).getName());
        switch(panel){
            case "Bank Account":
                editBankAcctPanel.setVisible(true);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                bank = (BankAccountCredential) RequestsHTTP.user.credentials.get(pos);
                bEditNameTF.setText(bank.getBankName());
                bEditUrlTF.setText(bank.getBankUrl());
                bEditUsernameTF.setText(bank.getUsername());
                bEditPasswordTF.setText(bank.getPassword());
                bEditAcctNumTF.setText(bank.getAcctNumber());
                bEditRoutNumTF.setText(bank.getRoutingNumber());
                break;
            case "Credit Card":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(true);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                credCard = (CreditCardCredential)RequestsHTTP.user.credentials.get(pos);
                ccEditBankNameTF.setText(credCard.getBankName());
                ccEditNumberTF.setText(credCard.getCardNumber());
                ccEditExpDateTF.setText(credCard.getExpDate());
                ccEditCardOwnerTF.setText(credCard.getNameOnCard());
                ccEditCcvTF.setText(credCard.getCcvNumber());
                ccEditTypeTF.setText(credCard.getType());
                break;
            case "Email":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(true);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                email = (EmailCredential)RequestsHTTP.user.credentials.get(pos);
                eEditLogPageTF.setText(email.getLoginUrl());
                eEditAddressTF.setText(email.getEmail());
                eEditPasswordTF.setText(email.getPassword());
                break;
            case "Login":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(true);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                login = (LoginCredential)RequestsHTTP.user.credentials.get(pos);
                lEditUsernameTF.setText(login.getUsername());
                lEditPasswordTF.setText(login.getPassword());
                lEditAssocEmailTF.setText(login.getAcctEmail());
                break;
            case "Software License":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(true);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                softl = (SoftwareLicenseCredential) RequestsHTTP.user.credentials.get(pos);
                slEditSoftNameTF.setText(softl.getSoftwareName());
                slEditKeyTF.setText(softl.getKey());
                slEditWebUrlTF.setText(softl.getUrl());
                slEditExpDateTF.setText(softl.getExpDate());
                break;
            case "SSN":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(true);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                ssn = (SocialSecurityCredential) RequestsHTTP.user.credentials.get(pos);
                ssnEditOwnerTF.setText(ssn.getOwnerName());
                ssnEditNumberTF.setText(ssn.getSsn());
                break;
            case "Website Login":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(true);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(false);
                
                web = (WebsiteCredential) RequestsHTTP.user.credentials.get(pos);
                weEditAssocEmailTF.setText(web.getEmail());
                weEditNameTF.setText(web.getWebsiteName());
                weEditPasswordTF.setText(web.getPassword());
                weEditUrlTF.setText(web.getUrl());
                weEditUsernameTF.setText(web.getUsername());
                break;
            case "Wireless":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(true);
                editCustomPanel.setVisible(false);
                
                wireless = (WirelessCredential) RequestsHTTP.user.credentials.get(pos);
                wiEditEncryptionTF.setText(wireless.getEncryption());
                wiEditNameTF.setText(wireless.getSsid());
                wiEditPasswordTF.setText(wireless.getPassword());
                wiEditUsernameTF.setText(wireless.getUsername());
                break;
            case "Custom":
                editBankAcctPanel.setVisible(false);
                editCredCardPanel.setVisible(false);
                editEmailPanel.setVisible(false);
                editLoginPanel.setVisible(false);
                editSoftLicPanel.setVisible(false);
                editSsnPanel.setVisible(false);
                editWebsitePanel.setVisible(false);
                editWirelessPanel.setVisible(false);
                editCustomPanel.setVisible(true);
                
                cust = (CustomCredential) RequestsHTTP.user.credentials.get(pos);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Error: Type of credential not valid", "ErrorBox: ", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bEditAcctNumTF;
    private javax.swing.JTextField bEditNameTF;
    private javax.swing.JTextField bEditPasswordTF;
    private javax.swing.JTextField bEditRoutNumTF;
    private javax.swing.JTextField bEditUrlTF;
    private javax.swing.JTextField bEditUsernameTF;
    private javax.swing.JTextField ccEditBankNameTF;
    private javax.swing.JTextField ccEditCardOwnerTF;
    private javax.swing.JTextField ccEditCcvTF;
    private javax.swing.JTextField ccEditExpDateTF;
    private javax.swing.JTextField ccEditNumberTF;
    private javax.swing.JTextField ccEditTypeTF;
    private javax.swing.JButton closeEditButton;
    private javax.swing.JLabel credNameTypeLabel;
    private javax.swing.JTextField eEditAddressTF;
    private javax.swing.JTextField eEditLogPageTF;
    private javax.swing.JTextField eEditPasswordTF;
    private javax.swing.JPanel editBankAcctPanel;
    private javax.swing.JPanel editCredCardPanel;
    private javax.swing.JPanel editCustomPanel;
    private javax.swing.JPanel editEmailPanel;
    private javax.swing.JPanel editLoginPanel;
    private javax.swing.JPanel editSoftLicPanel;
    private javax.swing.JPanel editSsnPanel;
    private javax.swing.JPanel editWebsitePanel;
    private javax.swing.JPanel editWirelessPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField lEditAssocEmailTF;
    private javax.swing.JTextField lEditPasswordTF;
    private javax.swing.JTextField lEditUsernameTF;
    private javax.swing.JButton saveEditButton;
    private javax.swing.JTextField slEditExpDateTF;
    private javax.swing.JTextField slEditKeyTF;
    private javax.swing.JTextField slEditSoftNameTF;
    private javax.swing.JTextField slEditWebUrlTF;
    private javax.swing.JTextField ssnEditNumberTF;
    private javax.swing.JTextField ssnEditOwnerTF;
    private javax.swing.JTextField weEditAssocEmailTF;
    private javax.swing.JTextField weEditNameTF;
    private javax.swing.JTextField weEditPasswordTF;
    private javax.swing.JTextField weEditUrlTF;
    private javax.swing.JTextField weEditUsernameTF;
    private javax.swing.JTextField wiEditEncryptionTF;
    private javax.swing.JTextField wiEditNameTF;
    private javax.swing.JTextField wiEditPasswordTF;
    private javax.swing.JTextField wiEditUsernameTF;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
